name: "Publish Package to NPM"

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create a release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v4
      - id: get-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: Delete a Release
        uses: liudonghua123/delete-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: v${{ steps.get-version.outputs.current-version }}
      - id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: v${{ steps.get-version.outputs.current-version }}
          draft: false
          generate_release_notes: true
  build:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - id: zipBuild
        name: Zip build artifacts
        run: cd build; zip -r ../release.zip *; cd ..
      - name: Upload release Zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./release.zip
          asset_name: release.zip
          asset_content_type: application/gzip
  publish-to-npm:
    name: Publish to npm
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
